config/routes.rb
Rails.application.routes.draw do
  root 'site/home#index'
  
  namespace :backoffice do
    get '', to: 'dashboard#index'
    get 'categories', to: 'categories#index'
    get 'category/new', to: 'categories#new'
    post 'category/create', to: 'categories#create'
    get 'category/:id/', to: 'categories#list_ads', as: 'category_ads'
  end
  
  namespace :site do
    get 'home/index'
    get 'example', to: 'home#example'
    get 'ad/:id', to: 'home#ad', as: 'ad'
    get 'category/:category_id', to: 'home#ad_by_category'
  end
  
  namespace :members do
    get 'index', to: 'members#index'
    get '', to: 'members#index'
    get 'new-ad', to: 'members#new_ad', as: 'new_ad'
    post 'create-ad', to: 'members#create_ad', as: 'create_ad'
    delete 'delete-ad/:ad_id', to:'members#destroy_ad', as: 'destroy_ad'
    get 'buying-ad/:ad_id', to: 'members#buy_ad', as: 'buy_ad'
    get 'ad/:ad_id/comment', to: 'members#new_comment', as:'new_comment'
    post 'ad/comment/new', to: 'members#create_comment', as: 'create_comment'
    post 'ad/respond/new', to: 'members#create_respond', as: 'create_respond'
  end
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  
  devise_for :members, controllers: {
    sessions: 'members/sessions'
  } 
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :ads, dependent: :destroy
 

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  # Definindo o layout
  layout 'backoffice'
  
  def index
    @categories = Category.all
    @category = Category.new
  end
  
  def new
    @category = Category.new
  end
  
  def create
    respond_to do |format|
      format.html {
        @category = Category.new(category_params)
        if @category.save
          flash[:notice] = "Categoria salva com sucesso"
          redirect_to backoffice_categories_path
        else
          flash[:notice] = "Não foi possível salvar a categoria"
          render new
        end
      }
      format.js {
        @category = Category.new(category_params)
        if @category.save
          flash[:notice] = "Categoria salva com sucesso"
        else
          flash[:notice] = "Não foi possível salvar a categoria"
        end
      }
    end
  end
  
  def list_ads
    @category = Category.find(params[:id])
    @ads = @category.ads
  end
  
  private
  
  def category_params
    params.require(:category).permit(:id, :description)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
  before_action :authenticate_admin!
  # Definindo o layout
  layout 'backoffice'
  
  def index
  end

end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/views/backoffice/categories/_categories_list.html.erb
<div class="row" id="table-div">
          <div class="col-md-5">
            <table class="table table-striped table-bordered">
              <thead>
                <th>#</th>
                <th>Categoria</th>
                <th>Posts</th>
                <th>Cliques</th>
                <th>Edição</th>
              </thead>
              <tbody id="insert-category">
                
                <% @count = 1 %>
                <% @categories[0, (@categories.size / 2)].each do |category| %>
                  <tr>
                    <td><%= @count %></td>
                    <td><%= link_to category.description, backoffice_category_ads_path(category.id) %></td>
                    <td><%= category.ads.count %></td>
                    <td>1</td>
                    <td>
                        <a href="#" class="btn btn-info btn-circle">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" class="btn btn-danger btn-circle">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                    <% @count += 1 %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-sm-1">
            
          </div>
          <div class="col-md-5">
            <table class="table table-striped table-bordered">
              <thead>
                <th>#</th>
                <th>Categoria</th>
                <th>Posts</th>
                <th>Cliques</th>
                <th>Edição</th>
              </thead>
              <tbody>
                <% @categories[(@categories.size / 2) + 1, @categories.size].each do |category| %>
                  <tr>
                    <td><%= @count %></td>
                    <td><%= link_to category.description, backoffice_category_ads_path(category.id) %></td>
                    <td><%= category.ads.count %></td>
                    <td>1</td>
                    <td>
                        <a href="#" class="btn btn-info btn-circle">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" class="btn btn-danger btn-circle">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                    <% @count += 1 %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

app/views/backoffice/categories/index.html.erb
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Categorias</h1>
    </div>
    
    <div>
        <a href="/backoffice/category/new">
        <button id="botao-nova-categoria-html" class="btn btn-success btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-check"></i>
            </span>
            <span class="text">Adicionar nova categoria (html)</span>
        </button>
        </a>

        <button id="botao-nova-categoria-js" class="btn btn-success btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-check"></i>
            </span>
            <span class="text">Adicionar nova categoria (js)</span>
        </button>
    
    </div>
    
    <div style="height: 25px">
      
    </div>
    <div id="nova-categoria" class="d-none">
        <%= form_for :category, remote: true, url: backoffice_category_create_path do |f|%>
            <div class="row">
                <div class="col-md-1">
                    <%= f.label :description, 'Categoria'%>
                </div>
                <div class="col-md-3">
                    <%= f.text_field :description, class:'form-control'%>
                </div>
            </div>
            <div style="height: 15px"></div>
            <%= f.submit 'Cadastrar', class:'btn btn-primary', id:'submit-button'%>
        <% end %>
        <div style="height: 25px"></div>
    </div>
    
    <div class="content">
      <div class="panel-body">
        <%= render 'categories_list' %>
      </div>
    </div>
  </div>
    
    

app/views/backoffice/categories/list_ads.html.erb
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800"><%= @category.description %></h1>
  </div>
  
  <div class="row" id="table-div">
    <div class="col-md-12">
      <table class="table table-striped table-bordered">
        <thead>
          <th>#</th>
          <th>Título</th>
          <th>Descrição</th>
        </thead>
        <tbody>
          <% @count = 1 %>
          <% @ads.each do |ad| %>
            <tr>
              <td><%= @count %></td>
              <td><%= ad.title %></td>
              <td><%= ad.description %></td>
            </tr>
            <% @count += 1 %>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Voltar', backoffice_categories_path, class:'btn btn-primary'%>
    </div>
  </div>
</div>

app/views/backoffice/categories/new.html.erb
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Nova Categoria</h1>
    </div>
    
    <%= form_for :category, url: backoffice_category_create_path do |f| %>
      <div class="form-group row">
        <div class="col-md-1">
           <%= f.label :description, 'Nome' %>
        </div>
        <div class="col col-md-3">
          <%= f.text_field :description, class:'form-control' %>
        </div>
      </div>
      <%= f.submit 'Cadastrar', class:'btn btn-primary'%>
    <% end%>