config/routes.rb
Rails.application.routes.draw do
  root 'site/home#index'
  
  namespace :backoffice do
    get '', to: 'dashboard#index'
    get 'categories', to: 'categories#index'
    get 'category/new', to: 'categories#new'
    post 'category/create', to: 'categories#create'
    get 'category/:id/', to: 'categories#list_ads', as: 'category_ads'
  end
  
  namespace :site do
    get 'home/index'
    get 'example', to: 'home#example'
    get 'ad/:id', to: 'home#ad', as: 'ad'
    get 'category/:category_id', to: 'home#ad_by_category'
  end
  
  namespace :members do
    get 'index', to: 'members#index'
    get '', to: 'members#index'
    get 'new-ad', to: 'members#new_ad', as: 'new_ad'
    post 'create-ad', to: 'members#create_ad', as: 'create_ad'
    delete 'delete-ad/:ad_id', to:'members#destroy_ad', as: 'destroy_ad'
    get 'buying-ad/:ad_id', to: 'members#buy_ad', as: 'buy_ad'
    get 'ad/:ad_id/comment', to: 'members#new_comment', as:'new_comment'
    post 'ad/comment/new', to: 'members#create_comment', as: 'create_comment'
    post 'ad/respond/new', to: 'members#create_respond', as: 'create_respond'
  end
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  
  devise_for :members, controllers: {
    sessions: 'members/sessions'
  } 
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :ads
  has_many :views, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :comments
  
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController
    before_action :authenticate_member!
    layout 'site'
    def index
        @member = current_member
        @ads = Ad.all
    end
    
    def buy_ad
        @ad = Ad.find(params[:ad_id])
        if current_member.id != @ad.member_id
            # @view = View.where(member_id: current_member.id, ad_id: @ad.id)
            # @view.update(type_view: '2')
            Purchase.create(member_id: current_member.id, ad_id: @ad.id)
            redirect_to members_index_path
        else
            redirect_to members_index_path
        end
    end
    
    def new_comment
        @member = current_member
        @ad_id = params[:ad_id]
        @comment = Comment.new
    end
    
    def create_comment
        respond_to do |format|
            format.html {
                @comment = Comment.new(comments_params)
                @comment.member_id = current_member.id
                @comment.comment_id = -1
                if @comment.save
                    flash[:notice] = 'Comentário salvo com sucesso'
                    redirect_to site_ad_path(@comment.ad_id)
                else
                    flash[:notice] = 'Não foi possível salvar o comentário'
                    redirect_to redirect_to site_ad_path(@comment.ad_id)
                end
            }
            format.js {
                @comment = Comment.new(comments_params)
                @comment.member_id = current_member.id
                @comment.comment_id = -1
                if @comment.save
                    flash[:notice] = 'Comentário salvo com sucesso'
                else
                    flash[:notice] = 'Não foi possível salvar o comentário'
                end
            }
        end
    end
    
    def create_respond
        respond_to do |format|
            format.html {
                
            }
            format.js {
                @comment = Comment.new(comments_params)
                @comment.member_id = current_member.id
                if @comment.save
                    flash[:notice] = 'Comentário salvo com sucesso'
                else
                    flash[:notice] = 'Não foi possível salvar o comentário'
                end   
            }
        end
    end
    
    def new_ad
        @member = current_member
        @ad = Ad.new
        @categories = Category.all
    end
    
    def create_ad
        @ad = Ad.new(ads_params)
        @ad.member_id = current_member.id
        if @ad.save
            flash[:noitce] = 'Anúncio criado com sucesso'
            redirect_to site_ad_path(@ad.id)
        else
            flash[:noitce] = 'Não foi posspível criar o anúncio'
            redirect_to members_index_path
        end
    end
    
    def destroy_ad
        @ad = Ad.find(params[:ad_id])
        if @ad.member_id == current_member.id
            if @ad.destroy
                flash[:noitce] = 'Anúncio apagado com sucesso'
                redirect_to members_index_path
            else
                flash[:noitce] = 'Não foi posspível apagar o anúncio'
                redirect_to members_index_path
            end
        else
            flash[:noitce] = 'Esse anúncio não lhe pertence'
            redirect_to members_index_path 
        end
    end
    
    private
    
    def ads_params
       params.require(:ad).permit(:title, :description, :category_id, :member_id, :price, :image)
    end
    
    def comments_params
        params.require(:comment).permit(:comment, :member_id, :ad_id, :comment_id)
    end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  layout 'login'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/members/members_helper.rb
module Members::MembersHelper
end

app/views/members/members/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-lg-3'>
      <div class="card my-4" style="">
        <img class="card-img-top" src="/profile-image.jpg" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>Nome:</b> <%= @member.name%> <%= @member.surname%> <br>
          <b>Data de nascimento: </b><%= @member.birthday.strftime('%d/%m/%Y') %>
          <% if @member.sex == 'M' %>
            <b>Sexo:</b> Masculino <br>
          <% else %>
            <b>Sexo:</b> Feminino <br>
          <% end %>
          <b>Membro desde:</b> <%= @member.created_at.strftime('%d/%m/%Y')%>
          </p>
        </div>
      </div>
      <div class="my-4">
        <%= link_to 'Novo Anúncio', members_new_ad_path, class:'btn btn-primary'%>
      </div>
    </div>

    <div class='col-lg-9'>
      <div class='my-4'>
        <h2>Histórico de Compras</h2>
        <div class='row'>
          <% @member.purchases.each do |purchase| %>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/site/ad/<%= purchase.ad_id %>"><%= @ads.find(purchase.ad_id).title %></a>
                  </h4>
                  <h5>$ <%= @ads.find(purchase.ad_id).price %></h5>
                  <p class="card-text"><%= @ads.find(purchase.ad_id).description %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">★ ★ ★ ★ ☆</small>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    
      <div class='my-4'>
        <h2>Últimos anuncios visualizados</h2>
        <div class='row'>
          <% @member.views.each do |view| %>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href=""><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/site/ad/<%= view.ad_id %>"><%= @ads.find(view.ad_id).title %></a>
                  </h4>
                  <h5>$ <%= @ads.find(view.ad_id).price %></h5>
                  <p class="card-text"><%= @ads.find(view.ad_id).description %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">★ ★ ★ ★ ☆</small>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class='my-4'>
        <h2>Seus anuncios</h2>
        <div class='row'>
          <% @member.ads.each do |ad| %>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/site/ad/<%= ad.id %>"><%= ad.title %></a>
                  </h4>
                  <h5>$ <%= ad.price%></h5>
                  <p class="card-text"><%= ad.description %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">★ ★ ★ ★ ☆</small><br>
                  <small><%= link_to 'Apagar', members_destroy_ad_path(ad.id), method: :delete, class:'btn btn-danger btn-sm', data: {confirm: 'Tem certeza que deseja apagar este anúncio'}%></small>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/members/members/new_ad.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-3'>
      <div class="card my-4" style="">
        <img class="card-img-top" src="/profile-image.jpg" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>Nome:</b> <%= @member.name%> <%= @member.surname%> <br>
          <b>Data de nascimento: </b><%= @member.birthday.strftime('%d/%m/%Y') %>
          <% if @member.sex == 'M' %>
            <b>Sexo:</b> Masculino <br>
          <% else %>
            <b>Sexo:</b> Feminino <br>
          <% end %>
          <b>Membro desde:</b> <%= @member.created_at.strftime('%d/%m/%Y')%>
          </p>
        </div>
      </div>
    </div>
    <div class='col-md-9'>
      <div class='my-4'>
        <h2>Novo Anúncio</h2>
        <div class='row my-4'>
          <%= form_for :ad, url: members_create_ad_path(@ad) do |f| %>
            <div class='form-group'>
              <div class='form-row'>
                <div class='col-md-3'>
                  <%= f.label :title, 'Título', class:'col-form-label font-weight-bold' %>
                </div>
                <div class='col'>
                  <%= f.text_field :title, class:'form-control', size: 150 %>
                </div>
              </div>
              <div class='form-row my-4'>
                <div class='col-md-3'>
                  <%= f.label :description, 'Descrição', class:'col-form-label font-weight-bold' %>
                </div>
                <div class='col'>
                  <%= f.text_area :description, class:'form-control' %>
                </div>
              </div>
              <div class='form-row my-4'>
                <div class='col-md-3'>
                  <%= f.label :price, 'Preço', class:'col-form-label font-weight-bold' %>
                </div>
                <div class='col'>
                  <%= f.text_field :price, class:'form-control' %>
                </div>
              </div>
              <div class='form-row my-4'>
                <div class='col-md-3'>
                  <%= f.label :category_id, 'Categoria', class:'col-form-label font-weight-bold' %>
                </div>
                <div class='col'>
                  <%= f.select :category_id, @categories.collect { |category| [category.description, category.id] }%>
                </div>
              </div>
            </div>
            <%= f.submit 'Cadastrar Anúncio', class:'btn btn-primary', id:'submit-button'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'plugins/jquery-price-format' %>
<script>
  document.addEventListener("turbolinks:load", function() {
    $("#ad_category_id").addClass('form-control');
    
    $('#ad_price').priceFormat({
      prefix: 'R$ ',
      centsSeparator: ',',
      thousandsSeparator: '.'
    });
    $("#submit-button").click(function(){
      $('#ad_price').priceFormat({
      prefix: '',
      centsSeparator: '.',
      thousandsSeparator: ','
    });
    })
  })
</script>

app/views/members/members/new_comment.html.erb
<div class="container">
  <div class="row">
    <div class='col-lg-3'>
      <div class="card my-4" style="">
        <img class="card-img-top" src="/profile-image.jpg" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><b>Nome:</b> <%= @member.name%> <%= @member.surname%> <br>
          <b>Data de nascimento: </b><%= @member.birthday.strftime('%d/%m/%Y') %>
          <% if @member.sex == 'M' %>
            <b>Sexo:</b> Masculino <br>
          <% else %>
            <b>Sexo:</b> Feminino <br>
          <% end %>
          <b>Membro desde:</b> <%= @member.created_at.strftime('%d/%m/%Y')%>
          </p>
        </div>
      </div>
    </div>

    <div class='col-lg-9'>
      <div class='my-4'>
        <h2>Novo Comentário</h2>
        <div class='row'>
          <%= form_for :comment, url: members_create_comment_path(@comment) do |f| %>
            <%= f.text_area :comment, class:'form-control', size:'150x10' %><br>
            <div class='d-none'>
              <%= f.text_field :ad_id, value: @ad_id %>
            </div>
            <%= f.submit 'Comentar', class:'btn btn-primary'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>