config/routes.rb
Rails.application.routes.draw do
  root 'site/home#index'
  
  namespace :backoffice do
    get '', to: 'dashboard#index'
    get 'categories', to: 'categories#index'
    get 'category/new', to: 'categories#new'
    post 'category/create', to: 'categories#create'
    get 'category/:id/', to: 'categories#list_ads', as: 'category_ads'
  end
  
  namespace :site do
    get 'home/index'
    get 'example', to: 'home#example'
    get 'ad/:id', to: 'home#ad', as: 'ad'
    get 'category/:category_id', to: 'home#ad_by_category'
  end
  
  namespace :members do
    get 'index', to: 'members#index'
    get '', to: 'members#index'
    get 'new-ad', to: 'members#new_ad', as: 'new_ad'
    post 'create-ad', to: 'members#create_ad', as: 'create_ad'
    delete 'delete-ad/:ad_id', to:'members#destroy_ad', as: 'destroy_ad'
    get 'buying-ad/:ad_id', to: 'members#buy_ad', as: 'buy_ad'
    get 'ad/:ad_id/comment', to: 'members#new_comment', as:'new_comment'
    post 'ad/comment/new', to: 'members#create_comment', as: 'create_comment'
    post 'ad/respond/new', to: 'members#create_respond', as: 'create_respond'
  end
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  
  devise_for :members, controllers: {
    sessions: 'members/sessions'
  } 
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/site/ads_controller.rb
class Site::AdController < ApplicationController
  before_action :authenticate_member!, only: [:new_ad]    
  layout 'site'
  def new_ad
      @ad = Ad.new
  end
  
  def create_ad
    @ad = Ad.new(ads_params)
    if @ad.save
      flash[:notice] = 'Anúncio criado com sucesso'
      redirect_to site_ad_path(params[:id])
    else
      flash[:notice] = 'Não foi possível criar o anuncio'
      redirect_to member_index_path
    end
  end
  
  def update_ad
  end
  
  def delete_ad
      # Esse método não deleta o anúncio, mas muda um valor de seu campo que o torna invisível
  end

  private
  
  def ads_params
    Params.require(:ad).permit(:title, :description, :category_id, :member_id, :price, :image)
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  before_action :find_ad, only: [:ad]
  before_action :list_categories, only: [:index, :example, :ad, :ad_by_category]
  # Para o layout posso fazer um before_action e chamar um método. O método definirá qual layout carregar.
  
  # Definindo o layout
  layout 'site'
  
  def index
    if member_signed_in?
      @ads = Ad.all.where.not(member_id: current_member.id).order('id DESC')
    else
      @ads = Ad.all.order('id DESC')
    end
  end
  
  def example
  end
  
  def ad
    visualization(params[:id])
    @member = Member.all
    @comments = Comment.all.where(ad_id: params[:id])
    puts @comments
    @comment = Comment.new
  end
  
  def ad_by_category
    @ads = Ad.where(category_id: params[:category_id])
  end

  private
  
  def find_ad
    @ad = Ad.find(params[:id])
  end
  
end

app/helpers/site/ad_helper.rb
module Site::AdHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/site/home/_categories.html.erb
<div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Categorias</h1>
            <div class="list-group">
                <% @categories.each do |category| %>
                    <a href="/site/category/<%= category.id%>" class="list-group-item" id="item-<%= category.id%>">
                        <%= category.description %>
                    </a>
                    <% end %>
            </div>

        </div>

app/views/site/home/ad.html.erb
<div class="container">

    <%= render 'categories' %>

      <div class="col-lg-9">

        <div class="card mt-4">
          <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
          <div class="card-body">
            <h3 class="card-title"><%= @ad.title%></h3>
            <p><small><%= @ad.category.description %></small></p>
            <h4>$<%= @ad.price %></h4>
            <p class="card-text"><%= @ad.description %></p>
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars
          </div>
          <%if @ad.member_id != current_member.id %>
            <div class='card-footer'><%= link_to 'Comprar Item', members_buy_ad_path(@ad.id), class:'btn btn-success', data: {confirm: 'Tem certeza que deseja comprar este item?'}%></div>
          <% end %>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
          <div class="card-header">
            Comentários
          </div>
          <div class="card-body">
            <div id='comments'>
              <% @ad.comments.where(comment_id: -1).each do |comment|%>
                <p><%= comment.comment %></p>
                <small class="text-muted">Commented by <% if current_member.id != comment.member_id %><%= @member.find(comment.member_id).name%> <%= @member.find(comment.member_id).surname%> <% else%> you <% end %> on <%= comment.created_at.strftime('%d/%m/%Y')%></small>
                <br>
                <%if !@ad.comments.where(comment_id: comment.id).empty? %>
                  <div class='card'>
                    <div class='card-header'>
                      <b>Resposta(s)</b>
                    </div>
                <% end %>
                <% @ad.comments.where(comment_id: comment.id).each do |respond| %>
                    <div class='card-body'>
                      <p><%= respond.comment %></p>
                      <small class="text-muted">Responded by <% if current_member.id != comment.member_id %><%= @member.find(comment.member_id).name%> <%= @member.find(comment.member_id).surname%> <% else%> you <% end %> on <%= comment.created_at.strftime('%d/%m/%Y')%></small>
                    </div>
                  <hr>
                <% end %>
                <%if !@ad.comments.where(comment_id: comment.id).empty? %>
                  </div>
                <% end %>
                <br>
                <button class='btn btn-success btn-sm' id='responder-<%=comment.id%>'>Responder Comentário</button>
                <div class='d-none' id='resposta-<%=comment.id%>'>
                  <script>
                    document.addEventListener("turbolinks:load", function() {
                      $("#responder-<%=comment.id%>").click(function(){
                        $("#resposta-<%=comment.id%>").removeClass("d-none");
                      });
                    })
                  </script>
                  <%= form_for :comment, url: members_create_respond_path, remote: true do |f| %>
                    <%= f.label :comment, 'Resposta'%>
                    <%= f.text_area :comment, class:'form-control'%>
                    <p class='d-none'>
                      <%= f.text_field :ad_id, value: @ad.id%>
                      <%= f.text_field :comment_id, value: comment.id%>
                    </p>
                    <br>
                    <%= f.submit 'Responder', class:'btn btn-success btn-sm'%>
                  <% end %>
                </div>
                <hr>
              <% end %>
             </div>
            <a href="/members/ad/<%= @ad.id%>/comment" class="btn btn-success">Comentar (HTML)</a>
            <hr>
            <div class='comment-section form-group'>
              <%= form_for :comment, remote: true, url: members_create_comment_path  do |f| %>
                <%= f.label :comment, 'Comentário', class:'form-group' %>
                <%= f.text_area :comment, class:'form-control', id:'comment-text' %>
                <p class='d-none'><%= f.text_field :ad_id, value: @ad.id %></p>
                <br>
                <%= f.submit 'Comentar', class:'btn btn-success', id:'comment-button'%>
              <% end %>
            </div>
          </div>
        </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>

  </div>
  <!-- /.container -->

app/views/site/home/ad_by_category.html.erb
<div class="container">
    <%= render 'categories' %>
        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                <% @ads.each do |ad| %>
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="/site/ad/<%= ad.id%>"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                      <a href="/site/ad/<%= ad.id%>"><%= ad.title%></a>
                    </h4>
                                <h5>$<%= ad.price %></h5>
                                <p class="card-text"><%= ad.description%></p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>
                    </div>
                <% end %>
                

            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
  </div>
</div>

app/views/site/home/example.html.erb
<div class="container">

    <%= render 'categories' %>

      <div class="col-lg-9">

        <div class="card mt-4">
          <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
          <div class="card-body">
            <h3 class="card-title">Product Name</h3>
            <h4>$24.99</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias iure, ducimus!</p>
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars
          </div>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
          <div class="card-header">
            Product Reviews
          </div>
          <div class="card-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <a href="#" class="btn btn-success">Leave a Review</a>
          </div>
        </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>

  </div>
  <!-- /.container -->

app/views/site/home/index.html.erb
<div class="container">
    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Categorias</h1>
            <div class="list-group">
                <% @categories.each do |category| %>
                    <a href="/" class="list-group-item" id="item-<%= category.id%>">
                        <%= category.description %>
                    </a>
                    <% end %>
            </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                <% @ads.each do |ad| %>
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="/site/ad/<%= ad.id%>"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                      <a href="/site/ad/<%= ad.id%>"><%= ad.title%></a>
                    </h4>
                                <h5>$<%= ad.price %></h5>
                                <p class="card-text"><%= ad.description%></p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>
                    </div>
                <% end %>
                

            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
  </div>
</div>